version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/car_rental
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    networks:
      - default

  database:
    image: postgres:alpine3.17
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: car_rental
    networks:
      - default


networks:
  default:
